SAMPLES: "/data2/home/pamesl/cbf_aml_pipeline/samples.json"

#  Reference Genome
REFERENCE: "/data1/scratch/pamesl/projet_cbf/data/hg19_data/reference_hg19/hg19.fa"

#  Panel of Normales parameters:
VCF_MAP: "/data1/scratch/pamesl/projet_cbf/data/map/sample_vcf.map"
reader_threads: 1
batch_size: 50
intervals_list: /data1/scratch/pamesl/projet_cbf/data/hg19_data/hg19_intervals.list
PON_VCF: "/data1/scratch/pamesl/projet_cbf/data/vcf/SJCBF_panel_of_normals.vcf.gz"

#  DataBase GenomicsDBImport
db_GDBI: "/data1/scratch/pamesl/projet_cbf/data/GenomicsDBImport"


#  Mutect2
germline_resource: "/data1/scratch/pamesl/projet_cbf/data/GnomAD/af-only-gnomad.raw.sites.hg19.vcf"
