SAMPLES: "samples.json"

#  Reference Genome
REFERENCE: "reference.fa"

#  Panel of Normales parameters:
VCF_MAP: "/data1/scratch/pamesl/projet_cbf/data/map/sample_vcf.map"
reader_threads: 1
batch_size: 50
intervals_size: 500
PON_VCF: "/data1/scratch/pamesl/projet_cbf/data/vcf/SJCBF_panel_of_normals.vcf.gz"

#  DataBase GenomicsDBImport
db_GDBI: "/data1/scratch/pamesl/projet_cbf/data/GenomicsDBImport"
