PROJECT_DIR: "/data1/scratch/pamesl/cbf_aml_pipeline/"
SAMPLES: "config/data.json"
sample_sheet: "config/sample_sheet.tsv"

#  Reference Genome
reference_GRCh37-lite: "/data1/scratch/pamesl/projet_cbf/data/b37_data/GRCh37-lite.fa"
reference_index_GRCh37-lite: "/data1/scratch/pamesl/projet_cbf/data/b37_data/GRCh37-lite.fai"


#  Mutect2 configuration
mutect2:
  to_use: True
  extra: "--panel-of-normals /data1/scratch/pamesl/projet_cbf/data/vcf/SJCBF_panel_of_normals.vcf.gz --germline-resource /data1/scratch/pamesl/projet_cbf/data/GnomAD/af-only-gnomad.raw.sites.b37.vcf --intervals /data1/scratch/pamesl/projet_cbf/data/b37_data/Broad.human.exome.b37.interval_list --independent-mates true"
  nthread: 8
  gnomad:
    files:
        raw: "/data1/scratch/pamesl/projet_cbf/data/GnomAD/af-only-gnomad.raw.sites.b37.vcf"
        biallelic: "/data1/scratch/pamesl/projet_cbf/data/GnomAD/af-only-gnomad.biallelic.sites.b37.vcf"


# Strelka configuration
strelka:
  to_use: False
  extra: ""


# Freebayes configuration
freebayes:
  to_use: False
  extra: "--pooled-continuous \
          --pooled-discrete \
          --genotype-qualities \
          --report-genotype-likelihood-max \
          --allele-balance-priors-off \
          --min-alternate-fraction 0.03 \
          --min-repeat-entropy 1 \
          --min-alternate-count 2 "


# somaticSniper configuration
somaticSniper:
  to_use: False
  extra: "-q 20 \
          -Q 20 "


# Annovar configuration
annovar:
  to_use: False
  extra: ""



# CalculateContamination
CalculateContamination:
        GetPileupSummaries:
                exac: "/data1/scratch/pamesl/projet_cbf/data/exac/small_exac_common_3_b37.vcf.gz"

# Funcotator TODO
funcotator:
      directory:  "/data1/scratch/pamesl/projet_cbf/funcotator_dataSources.v1.6.20190124g"

# MarkDuplicates
mark_duplicates:
  spark:
    nthread: 40
  classic:
    nthread: 10

# BQSRPipelineSpark NOT USED
BQSRPipelineSpark:
  nthread: 10

# MergeSamFiles
MergeSamFiles:
  nthread: 5

# Samtools
samtools:
  nthread: 5

# FilterMutectCalls
FilterMutectCalls:
  nthread: 10

FASTQC:
  DIR: "results/qualities/"
  to_use: False

#  Panel of Normales parameters:
panelsOfNormals:
  to_use: False
VCF_MAP: "/home/data/pameslin/cbf_aml_pipeline/map/sample_vcf.map"
reader_threads: 1
batch_size: 50
intervals_list: "/data1/scratch/pamesl/projet_cbf/data/b37_data/Broad.human.exome.b37.interval_list"
bed_intervals: "/data1/scratch/pamesl/projet_cbf/data/b37_data/Broad.human.exome.b37_no_single_base.bed.gz"
PON_VCF: "/data1/scratch/pamesl/projet_cbf/data/vcf/SJCBF_panel_of_normals.vcf.gz"

#  DataBase GenomicsDBImport
db_GDBI: "/data1/scratch/pamesl/projet_cbf/data/GenomicsDBImport"

known-sites:
  dbsnp_138: "/data1/scratch/pamesl/projet_cbf/data/dbSNP/dbsnp_138.b37.vcf"
  mills_1000G: "/data1/scratch/pamesl/projet_cbf/data/mills_1000G/Mills_and_1000G_gold_standard.indels.b37.vcf"
