# Project Metadata
project_dir: "/data1/scratch/pamesl/cbf_aml_pipeline/"
sample_sheet: "config/sample_sheet.tsv"
token: "test04"

#  Reference Genome
reference: "/mnt/d/bioinfo_data/ref/Homo_sapiens.GRCh38.dna.chromosome.22.fa"
reference_index: "/mnt/d/bioinfo_data/ref/Homo_sapiens.GRCh38.dna.chromosome.22.fa.fai"


#  Mutect2 configuration
mutect2:
  activate: False
  extra: "--panel-of-normals /data1/scratch/pamesl/projet_cbf/data/vcf/SJCBF_panel_of_normals.vcf.gz --germline-resource /data1/scratch/pamesl/projet_cbf/data/GnomAD/af-only-gnomad.raw.sites.b37.vcf --intervals /data1/scratch/pamesl/projet_cbf/data/b37_data/Broad.human.exome.b37.interval_list --independent-mates false"
  nthread: 8
  gnomad:
    files:
        raw: "/mnt/d/bioinfo_data/ref/flt3.fa"
        biallelic: "/mnt/d/bioinfo_data/ref/flt3.fa"


# Strelka configuration
strelka:
  activate: False
  extra: ""


# Freebayes configuration
freebayes:
  activate: False
  extra: "--pooled-continuous \
          --pooled-discrete \
          --genotype-qualities \
          --report-genotype-likelihood-max \
          --allele-balance-priors-off \
          --min-alternate-fraction 0.03 \
          --min-repeat-entropy 1 \
          --min-alternate-count 2 "


# somaticSniper configuration
somaticSniper:
  activate: False
  extra: "-q 20 \
          -Q 20 "


# Annovar configuration
annovar:
  activate: False
  extra: ""


# CalculateContamination
CalculateContamination:
        GetPileupSummaries:
                exac: "/mnt/d/bioinfo_data/ref/flt3.fa"


# Funcotator
funcotator:
      directory:  "/mnt/d/bioinfo_data/ref/flt3.fa"


# MarkDuplicates
mark_duplicates:
  spark:
    nthread: 40
  classic:
    nthread: 10


# BQSRPipelineSpark NOT USED
BQSRPipelineSpark:
  nthread: 10


# MergeSamFiles
MergeSamFiles:
  nthread: 5


# Samtools
samtools:
  nthread: 5


# FilterMutectCalls
FilterMutectCalls:
  nthread: 10


# FastQC
FASTQC:
  DIR: "results/qualities/"
  activate: True


# Sequenza
sequenza:
  activate: True
  gcfile: "config/sequenza/gc.file"
  chrom: "config/sequenza/chrom.txt"


VariantFiltering:
  diploid_variants: True
  oxog_filtering: False



#  Panel of Normales parameters:
panelsOfNormals:
  activate: True
VCF_MAP: "/mnt/d/bioinfo_data/ref/flt3.fa"
reader_threads: 1
batch_size: 50
intervals_list: "/mnt/d/bioinfo_data/ref/flt3.fa"
bed_intervals: "/mnt/d/bioinfo_data/ref/flt3.fa"
PON_VCF: "/mnt/d/Pipelines/cbf_aml_pipeline/results/SJCBF_panel_of_normals.vcf.gz"


#  DataBase GenomicsDBImport
db_GDBI: "/data1/scratch/pamesl/projet_cbf/data/GenomicsDBImport"
known-sites:
  dbsnp_138: "/mnt/d/bioinfo_data/ref/flt3.fa"
  mills_1000G: "/mnt/d/bioinfo_data/ref/flt3.fa"
