# Project Metadata
sample_sheet: "config/sample_sheet.tsv"
token: "WES_SJCBF040"

#  Reference Genome
reference: "/home/puissant/cbf_aml_pipeline/ressources/hg19_v0_Homo_sapiens_assembly19.fasta"
reference_index: "/home/puissant/cbf_aml_pipeline/ressources/hg19_v0_Homo_sapiens_assembly19.fasta.fai"


#  Mutect2 configuration
mutect2:
  activate: False
  extra: ""
  nthread: 8
  intervals: "/home/puissant/cbf_aml_pipeline/ressources/Broad.human.exome.b37.interval_list"
  gnomad:
    files:
        raw: "/home/puissant/cbf_aml_pipeline/ressources/af-only-gnomad.raw.sites.b37.vcf.gz"


# Strelka configuration
strelka:
  activate: False
  extra: ""


# Freebayes configuration
freebayes:
  activate: False
  extra: "--pooled-continuous \
          --pooled-discrete \
          --genotype-qualities \
          --report-genotype-likelihood-max \
          --allele-balance-priors-off \
          --min-alternate-fraction 0.05 \
          --min-repeat-entropy 1 \
          --min-alternate-count 2"


# somaticSniper configuration
somaticSniper:
  activate: False
  extra: "-q 20 \
          -Q 20 "



# CalculateContamination
CalculateContamination:
        GetPileupSummaries:
                exac: "/mnt/d/bioinfo_data/ref/flt3.fa"



# MarkDuplicates
mark_duplicates:
  nthread: 40
  spark:
  classic:
    nthread: 10



# MergeSamFiles
MergeSamFiles:
  nthread: 5


# Samtools
samtools:
  nthread: 5


# FilterMutectCalls
FilterMutectCalls:
  nthread: 10


# FastQC
FASTQC:
  DIR: "results/qualities/"
  activate: False


# Sequenza
sequenza:
  activate: False
  gcfile: "config/sequenza/gc.file"
  chrom: "config/sequenza/chrom.txt"


VariantFiltering:
  diploid_variants: False
  pass: False
  mutect2_strelka2_intersection: True



#  Panel of Normales parameters:
panelsOfNormals:
  activate: False
VCF_MAP: "/mnt/d/bioinfo_data/ref/flt3.fa"
reader_threads: 1
batch_size: 50
bed_intervals: "/home/puissant/cbf_aml_pipeline/ressources/intervals/Broad.human.exome.b37.bed.gz"


#  DataBase GenomicsDBImport
known-sites:
  dbsnp_138: "/home/puissant/cbf_aml_pipeline/ressources/G37/dbsnp_138.b37.vcf.gz"
  mills_1000G: "/home/puissant/cbf_aml_pipeline/ressources/G37/Mills_and_1000G_gold_standard.indels.b37.vcf.gz"
